export const cardList = [
  {
    id:1,
    name: '33 слова о дизайне',
    image: require ('../images/movie-1.png'),
    duration: 107,
  },
  {
    id:2,
    name: 'Киноальманах «100 лет дизайна»',
    image: require ('../images/movie-2.png'),
    duration: 63,
  },
  {
    id:3,
    name: 'В погоне за Бенкси',
    image: require ('../images/movie-3.png'),
    duration: 102,
  },
  {
    id:4,
    name: 'Баския: Взрыв реальности',
    image: require ('../images/movie-4.png'),
    duration: 81,
  },
  {
    id:5,
    name: 'Бег это свобода',
    image: require ('../images/movie-5.png'),
    duration: 104,
  },
  {
    id:6,
    name: 'Книготорговцы',
    image: require ('../images/movie-6.png'),
    duration: 97,
  },
  {
    id:7,
    name: 'Когда я думаю о Германии ночью',
    image: require ('../images/movie-7.png'),
    duration: 116,
  },
  {
    id:8,
    name: 'Gimme Danger. История Игги и The Stooges',
    image: require ('../images/movie-8.png'),
    duration: 119,
  },
  {
    id:9,
    name: 'Дженис: Маленькая девочка грустит',
    image: require ('../images/movie-9.png'),
    duration: 102,
  },
  {
    id:10,
    name: 'Соберись перед прыжком',
    image: require ('../images/movie-10.png'),
    duration: 70,
  },
  {
    id:11,
    name: 'Пи Джей Харви: A dog called money',
    image: require ('../images/movie-11.png'),
    duration: 64,
  },
  {
    id:12,
    name: 'По волнам: Искусство звука в кино',
    image: require ('../images/movie-12.png'),
    duration: 67,
  },
  {
    id:13,
    name: '33 слова о дизайне',
    image: require ('../images/movie-1.png'),
    duration: 107,
  },
  {
    id:14,
    name: 'Киноальманах «100 лет дизайна»',
    image: require ('../images/movie-2.png'),
    duration: 63,
  },
  {
    id:15,
    name: 'В погоне за Бенкси',
    image: require ('../images/movie-3.png'),
    duration: 102,
  },
  {
    id:16,
    name: 'Баския: Взрыв реальности',
    image: require ('../images/movie-4.png'),
    duration: 81,
  },
  {
    id:17,
    name: 'Бег это свобода',
    image: require ('../images/movie-5.png'),
    duration: 104,
  },
  {
    id:18,
    name: 'Книготорговцы',
    image: require ('../images/movie-6.png'),
    duration: 97,
  },
  {
    id:19,
    name: 'Когда я думаю о Германии ночью',
    image: require ('../images/movie-7.png'),
    duration: 116,
  },
  {
    id:20,
    name: 'Gimme Danger. История Игги и The Stooges',
    image: require ('../images/movie-8.png'),
    duration: 119,
  },
  {
    id:21,
    name: 'Дженис: Маленькая девочка грустит',
    image: require ('../images/movie-9.png'),
    duration: 102,
  },
  {
    id:22,
    name: 'Соберись перед прыжком',
    image: require ('../images/movie-10.png'),
    duration: 70,
  },
  {
    id:23,
    name: 'Пи Джей Харви: A dog called money',
    image: require ('../images/movie-11.png'),
    duration: 64,
  },
  {
    id:24,
    name: 'По волнам: Искусство звука в кино',
    image: require ('../images/movie-12.png'),
    duration: 67,
  },
];

export const savedCardList = [
  {
    id:1,
    name: '33 слова о дизайне',
    image: require ('../images/movie-1.png'),
    duration: 107,
  },
  {
    id:2,
    name: 'Киноальманах «100 лет дизайна»',
    image: require ('../images/movie-2.png'),
    duration: 63,
  },
  {
    id:3,
    name: 'В погоне за Бенкси',
    image: require ('../images/movie-3.png'),
    duration: 102,
  },
]